### ISSUE TITLE
Pluck method for the store.

### ISSUE THREAD

**Issue by Jafa80** [Chekote/noun-store#26]
It would be nice if we could pluck values from store or at least reset specific key. That allows us to prevent it being used again.
For example:
```php
$model = new Model();
$store->set('Model', $model);
//Returns the value and removes it from nouns array.
$m1 = $store->pluck('Model');
// Or we could use to ensure that Model key has no values:
$m1 = $store->get('Model');
$store->reset('Model');

if($someCondition) {
   $model2 = new Model();
   $store->set('Model', $model2);
}
$m2 = $store->pluck('Model');
```
In this case when $model2 is not set to store, then $m1 != $m2

**Comment by Chekote** [comment]
The noun store is intended to be an immutable history of the nouns that were referred to during execution. I feel that adding methods to pluck or reset a specific key is an indication that the package is being used for something, or in a way that it was not intended for.

If you could post a real-world example of what you're trying to do, maybe I can offer some advice on how to use the noun-store, or whether maybe it's not the right tool for the job.
